EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-mmc.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-snd.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-panel.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-bt.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-camera.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-input.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-misc.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-pm.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-regulator.o

#obj-$(CONFIG_MACH_MSM7X27_PECAN) += lge_errorhandler.o #LGE_CHANGE [blue.park@lge.com] 2009-04-04 <For Error Handler>
obj-$(CONFIG_MACH_MSM7X27_PECAN) += lge_temp.o # LGE_CHANGE neo.kang@lge.com just for Line PV. It will be removed
obj-$(CONFIG_MACH_MSM7X27_PECAN) += lge_mtd_direct_access.o # LGE_CHANGE neo.kang@lge.com just for Line PV. It will be removed.

