EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-mmc.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-snd.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-panel.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-bt.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-camera.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-input.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-misc.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-pm.o
obj-$(CONFIG_MACH_MSM7X27_PECAN) += board-pecan-regulator.o

