EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools


obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-mmc.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-snd.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-panel.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-bt.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-camera.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-input.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-misc.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-pm.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-regulator.o
