EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-mmc.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-snd.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-panel.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-bt.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-camera.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-input.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-misc.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-pm.o
