EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-mmc.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-snd.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-panel.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-bt.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-camera.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-input.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-misc.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-pm.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-regulator.o

