EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-mmc.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-snd.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-panel.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-bt.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-camera.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-input.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-misc.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-pm.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-regulator.o

